### ISSUE TITLE
Chart labels are created 2x as many times as necessary

### ISSUE THREAD

**Issue by samreid** [phetsims/griddle#72] opened 2020-10-06 21:47 UTC
From https://github.com/phetsims/circuit-construction-kit-common/issues/601#issuecomment-704384701

> I noticed that even though it only have 5 labels, it creates them twice.  You can test this by adding this line where the vertical label text is created:

```js
console.log('create vertical label')
```

> Then when you zoom in or out in CCK AC Voltmeter, instead of creating 5 new labels, it creates 10 each time.  This is likely in the noise and would not block publication, but I thought I should mention it.

**Comment by jessegreenberg** [comment] 2020-11-23 20:10
It looks like CCK is no longer using SeismographNode or XYChartNode, Ill try to reproduce in ESP.

**Comment by jessegreenberg** [comment] 2020-11-23 20:14
Zooming in or out of the XYChartNode in EnergySkatePark by clicking on the ZoomButtons in EnergyGraphAccordionBox, I am only seeing one call to XYChartNode.redrawLabels when I put a console statement in that function.

**Comment by jessegreenberg** [comment] 2020-11-23 20:18
OK, I do see two calls to XYChartNode.redrawVerticalLabels when I use the SeismographNode in the griddle demo.

EDIT: We have one call from SeismographNode, which causes a redraw of labels when line spacings are set in response to `verticalRangeProperty` changing. The other call is from the listener on the modelViewTransformProperty in XYChartNode.

**Comment by jessegreenberg** [comment] 2020-11-23 20:28
I guess this seems fairly reasonable to me. The labels will need to ensure they are drawn correctly if grid line spacings change, or if the modelViewTransform for the chart changes. So maybe we can try to only recreate content if we detect a change somehow.

**Comment by jessegreenberg** [comment] 2020-11-23 20:52
I was just about to commit a change that would only draw labels when the positions of labels had changed, it looked something like 
```js
redrawVerticalLabels() {

        const yPositions = this.gridNode.getLinePositionsInGrid( this.majorHorizontalLineSpacing, GridNode.LineType.MAJOR_HORIZONTAL );
        if ( !_.isEqual( yPositions, this.verticalGridLinePositions ) ) {
          this.verticalGridLinePositions = yPositions;

          // remove old labels, create new labels and add
        }
}
```

But that didn't work with functions like `setVerticalGridLabelNumberOfDecimalPlaces`, labels need to be redrawn in that case without a change in position.

Should we check if positions or precision of labels have changed before redrawing labels? Does this seem like the right path @samreid?

**Comment by samreid** [comment] 2020-11-23 21:07
I'm not sure that level of optimization is necessary, unless there is a simulation-specific bottleneck that can be traced to this implementation.

**Comment by jessegreenberg** [comment] 2020-11-23 21:49
Sounds good, I agree. I think that is especially true since new code for charts are going to start using bamboo. I am going to close this issue.

**Closed as completed by jessegreenberg** 2020-11-23 21:49 UTC
Labels: dev:code-review
