### ISSUE TITLE
Precision looks incorrect for GridNode assertions

### ISSUE THREAD

**Issue by samreid** [phetsims/griddle#61] opened 2020-08-12 01:20 UTC
From https://github.com/phetsims/griddle/issues/59, it looks like the tolerance is a bit too high:

```js
      // allow for precision errors, see phetsims/scenery-phet#601
      assert && assert( Utils.equalsEpsilon( majorSpacing % minorSpacing, 0, 1E10 ) ||
                        Utils.equalsEpsilon( majorSpacing % minorSpacing - minorSpacing, 0, 1E10 ), 'minor spacing must be a multiple of major spacing' );
```

Did you mean 1E-10?

**Comment by jessegreenberg** [comment] 2020-09-08 19:16
Wow, yes I did, thanks!

**Comment by jessegreenberg** [comment] 2020-09-08 19:24
Fixed in the above commit. The assertion was basically not checking anything before so running local aqua now that it is as intended.

**Comment by jessegreenberg** [comment] 2020-09-08 19:57
So far so good on local testing and the latest iteration on CT is ~older~ newer than this commit. Closing.

**Closed as completed by jessegreenberg** 2020-09-08 19:57 UTC
