### ISSUE TITLE
chart's cursor doesn't stop moving when you press on it

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/griddle#73] opened 2020-11-02 19:44 UTC
To reproduce:

1. Run griddle demo
2. Select "XYCursorChartNode" from the combo box
3. Press on the chart's cursor (but do not drag) before it reaches the right edge of the graph. The cursor is now connected to the pointer's drag listener, but the cursor keeps moving. 
4. Wait 1 second, then drag.  Now the cursor jumps back to where the pointer is.

This is not a good UX, and had me really confused the first time I tried to use a XYCursorChartNode. For lack of a "usability" label, I'm going to label this as a bug.  On press, the cursor should stop moving, and should remain at the pointer position. 

@jessegreenberg is the `@author`, so assigning to him.

**Comment by samreid** [comment] 2020-11-21 03:12
We will probably need to maintain the griddle cursor chart for a while, but I would like to add one to bamboo.

**Comment by jessegreenberg** [comment] 2020-11-23 19:52
This behavior was caused by a problem in the demo, it stopped recording data on the optional `drag` callback rather than the optional `startDrag` of `cursorOptions`. Fixed in the above commit, closing.

**Closed as completed by jessegreenberg** 2020-11-23 19:52 UTC
Labels: type:bug
